import fs from "node:fs";
import path from "node:path";

export interface WrapperSpec {
  /** Name of the binary as it will appear on PATH inside the env. */
  name: string;
  /** Absolute path to the real binary to exec. */
  realBin: string;
  /** Absolute path to envs/<name>/home — set as HOME for the child. */
  fakeHome: string;
  /** Additional env vars to export before exec. */
  extraEnv?: Record<string, string>;
}

export function writeWrapper(binDir: string, w: WrapperSpec): string {
  fs.mkdirSync(binDir, { recursive: true });
  const dest = path.join(binDir, w.name);
  const lines = [
    "#!/bin/sh",
    "# Generated by coffeeenv — HOME-hijack wrapper",
    `export HOME=${sh(w.fakeHome)}`,
    `export XDG_CONFIG_HOME=${sh(path.join(w.fakeHome, ".config"))}`,
  ];
  for (const [k, v] of Object.entries(w.extraEnv ?? {})) {
    lines.push(`export ${k}=${sh(v)}`);
  }
  lines.push(`exec ${sh(w.realBin)} "$@"`);
  fs.writeFileSync(dest, lines.join("\n") + "\n", { mode: 0o755 });
  return dest;
}

function sh(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}
