package state

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/coffeectx/coffeeenv/internal/sys"
)

func init() { Register(&envHandler{}) }

// envHandler manages environment variables in a single coffeeenv-owned file,
// ~/.config/coffeeenv/activate.sh, which the user sources from their shell rc.
// It never edits the user's rc directly. Each env state independently upserts
// its own `export` line, so multiple env states converge the same file.
type envHandler struct{}

type envDesired struct {
	Name   string `json:"name"`
	Value  string `json:"value"`
	Target string `json:"target"`
}

// file returns the managed activate-file path for this env var: the explicit
// target, or the global default.
func (d *envDesired) file() string {
	if d.Target != "" {
		return sys.ExpandPath(d.Target)
	}
	return activatePath()
}

// envObserved is the current value of this var in the managed file ("" if unset)
// and whether it was present at all.
type envObserved struct {
	Present bool
	Value   string
}

func (envHandler) Type() string { return "env" }

func (envHandler) Decode(rs RawState) (Desired, error) {
	var p envDesired
	if err := decodeParams(rs, &p); err != nil {
		return nil, err
	}
	if p.Name == "" {
		return nil, errors.New("env: name is required")
	}
	return &p, nil
}

func (envHandler) Read(_ context.Context, desired Desired) (Observed, error) {
	d := desired.(*envDesired)
	vars, err := readActivate(d.file())
	if err != nil {
		return nil, err
	}
	v, ok := vars[d.Name]
	return &envObserved{Present: ok, Value: v}, nil
}

func (envHandler) Diff(desired Desired, observed Observed) ([]Action, error) {
	d := desired.(*envDesired)
	o := observed.(*envObserved)
	if o.Present && o.Value == d.Value {
		return nil, nil
	}
	verb := "set"
	if o.Present {
		verb = "update"
	}
	return []Action{{
		StateName: d.Name,
		Kind:      "set-env",
		Summary:   fmt.Sprintf("%s %s=%s in %s", verb, d.Name, d.Value, displayPath(d.file())),
		Payload:   *d,
	}}, nil
}

func (envHandler) Apply(_ context.Context, a Action) error {
	d := a.Payload.(envDesired)
	vars, err := readActivate(d.file())
	if err != nil {
		return err
	}
	vars[d.Name] = d.Value
	return writeActivate(d.file(), vars)
}

// --- managed activate.sh helpers ---

const activateHeader = "# Generated by coffeeenv — do not edit. Source this from your shell rc."

func activatePath() string {
	if dir := os.Getenv("XDG_CONFIG_HOME"); dir != "" {
		return filepath.Join(dir, "coffeeenv", "activate.sh")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "coffeeenv", "activate.sh")
}

// displayPath shortens a home-relative path to ~/… for readable plan output.
func displayPath(p string) string {
	if home, err := os.UserHomeDir(); err == nil {
		if rel, err := filepath.Rel(home, p); err == nil && !strings.HasPrefix(rel, "..") {
			return "~/" + rel
		}
	}
	return p
}

func readActivate(path string) (map[string]string, error) {
	vars := map[string]string{}
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return vars, nil
		}
		return nil, err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		rest, ok := strings.CutPrefix(line, "export ")
		if !ok {
			continue
		}
		name, val, ok := strings.Cut(rest, "=")
		if !ok {
			continue
		}
		vars[strings.TrimSpace(name)] = unquoteShell(strings.TrimSpace(val))
	}
	return vars, sc.Err()
}

func writeActivate(path string, vars map[string]string) error {
	names := make([]string, 0, len(vars))
	for n := range vars {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(activateHeader + "\n")
	for _, n := range names {
		fmt.Fprintf(&b, "export %s=%s\n", n, quoteShell(vars[n]))
	}
	return sys.WriteFileAtomic(path, []byte(b.String()), 0o644)
}

// quoteShell wraps a value in single quotes, escaping embedded single quotes.
func quoteShell(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func unquoteShell(s string) string {
	if len(s) >= 2 && s[0] == '\'' && s[len(s)-1] == '\'' {
		inner := s[1 : len(s)-1]
		return strings.ReplaceAll(inner, `'\''`, "'")
	}
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}
